#This is demo file that contains the configuration properties for the Vatroslav-Backend application.
#Real file should be created as application.properties and should contain the actual values for the properties.
#Location of the file should be in src/main/resources/ directory of the project.
spring.application.name=Vatroslav-Backend

server.address=0.0.0.0
server.port=8080
server.shutdown=graceful

spring.lifecycle.timeout-per-shutdown-phase=30s

logging.file.name=

spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

app.admin.email=
app.admin.password=
app.admin.firstName=
app.admin.lastName=

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=