spring.application.name=backend

server.address=0.0.0.0
server.port=8080

#spring.mvc.cors.allowed-origins=https://test.hr

#spring.datasource.url=jdbc:postgresql://localhost:5432/vatroslav
#spring.datasource.username=vatroslav
#spring.datasource.password=123456789

spring.datasource.url=jdbc:postgresql://localhost:5432/inventarbaza
spring.datasource.username=postgres
spring.datasource.password=123456789

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB