spring.application.name=backend

server.address=0.0.0.0
server.port=8080

#spring.mvc.cors.allowed-origins=https://test.hr

#spring.datasource.url=jdbc:postgresql://dpg-cu2p9i3qf0us73bqmam0-a.frankfurt-postgres.render.com/inventar_o5gp
#spring.datasource.username=inventar_o5gp_user
#spring.datasource.password=KHQvoHMgMFgMYEtyAk6y4AbGxjzMFIxl

#spring.datasource.url=jdbc:postgresql://localhost:5432/inventarbaza
#spring.datasource.username=luka
#spring.datasource.password=123456789

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update

spring.datasource.url=jdbc:postgresql://dpg-d0isp73e5dus739ueasg-a.frankfurt-postgres.render.com/inventar_xesx
spring.datasource.username=inventar_xesx_user
spring.datasource.password=QWcBYuS2vTODWvLcR6h9s3P8lCtoleS8